unstable_features = true

#stable current features
hard_tabs = true
max_width = 120
newline_style = "Unix"

#unstable features (That are stable for v2.0)
match_block_trailing_comma = true
use_field_init_shorthand = true

#unstable features
blank_lines_upper_bound = 2
imports_layout = "HorizontalVertical"
merge_imports = true
overflow_delimited_expr = true
reorder_impl_items = true

